version: '3.9'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - redis

  display:
    build: ./display
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
