version: '3.9'

services:
  redis:
    image: redis:latest
    container_name: qmaster_redis
    ports:
      - "6379:6379"

  api:
    build: ./api
    container_name: qmaster_api
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  display:
    build: ./display
    container_name: qmaster_display
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
