version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

  number-service:
    build: ./number-service
    container_name: number-service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped

  queue-service:
    build: ./queue-service
    container_name: queue-service
    ports:
      - "5000:8000"
    depends_on:
      - redis
      - number-service
      - rabbitmq
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NUMBER_SERVICE_URL=http://number-service:8000
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: unless-stopped

  display-service:
    build: ./display-service
    container_name: display-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - queue-service
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - QUEUE_SERVICE_URL=http://queue-service:8000
    restart: unless-stopped
